### ISSUE TITLE
Fatal error after installation of tagentry plugin

### ISSUE THREAD

**Issue by tmo26** [sphaira-dev/dokuwiki-tagentry#2]
Release 2018-04-22a "Greebo"
tagentry version: 2018-02-15

Immediately after installation of tagentry plugin I get this error message at the top of the page (I couldn't copy & paste the text, therefore as image):
![grafik](https://user-images.githubusercontent.com/12309103/42408339-6b71d7e6-81cb-11e8-935d-230d5aac6ee4.png)
and the page is shown unformatted.

Removing the tagentry plugin immediately resolved the problem: No error message any more and page shows up correctly formatted.

**Comment by Matt-V50** [comment]
same

**Comment by GJRobert** [comment]
A crude solution found here: https://forum.dokuwiki.org/thread/16928 (in Deutsch), involving adding two lines
```
@ini_background_panel: #ffffff;
@ini_text_panel: #000000;
```
in the beginning of /lib/plugins/tagentry/style.css, so that the two variables are defined again.

But should they not be defined elsewhere in the first place? Why did this plugin become broken after Greebo?

**Comment by Michaelsy** [comment]
> Why did this plugin become broken after Greebo?

An idea I have for this question: In Greebo, the LESS compiler has been replaced by a more recent fork from another developer. Maybe the compiler used now is more restrictive.

**Comment by tmo26** [comment]
Issue solved with update to latest plugin version (2019-10-17).
